from datetime import date
from decimal import Decimal
from typing import List, Optional
from pydantic import BaseModel
from fastapi import APIRouter, Depends

from app.services.dataset_provider import get_repository, get_current_user_id, resolve_and_validate_user_id
from app.services.affordability_agent.data.twin_factory import FinancialTwinFactory
from app.services.affordability_agent.models.resolved_event import ResolvedFinancialEvent

router = APIRouter()

class ExpenseItem(BaseModel):
    id: str
    name: str
    category: str
    amount: Decimal
    currency: str
    frequency: str
    next_date: date
    flexibility: str
    is_protected: bool

class ExpenseSummary(BaseModel):
    total_relevant: int
    protected_total: Decimal
    flexible_total: Decimal

class ExpensesResponse(BaseModel):
    items: List[ExpenseItem]
    summary: ExpenseSummary

@router.get("", response_model=ExpensesResponse)
def list_expenses(user_id: str = None):
    """
    List all current/upcoming expenses that affect available capacity.
    """
    uid = resolve_and_validate_user_id(user_id)
    repo = get_repository()
    factory = FinancialTwinFactory(repo)
    
    # We must determine "today" based on the max date in the canonical user's ledger
    # so we're not filtering out all of 2024 with a 2026 current date.
    events = repo.get_events(uid)
    # We use the user's latest event date as 'today' to establish their financial world context
    today = max((ev.settlement_date or ev.event_date) for ev in events) if events else date.today()
        
    twin = factory.build(uid, today)
    
    # We want future scheduled outflows and recurring expenses
    from app.services.affordability_agent.recurring import RecurringPatternDetector
    from datetime import timedelta
    
    detector = RecurringPatternDetector()
    past_events = [ev for ev in events if (ev.settlement_date or ev.event_date) <= today]
    projected = detector.detect_and_project(past_events, today, today + timedelta(days=90))
    all_events = events + projected
    
    from app.services.affordability_agent.data.classification import is_essential_outflow, is_flexible_outflow, is_ignored_for_forecast
    
    upcoming_by_key = {}
    
    for ev in all_events:
        if ev.direction != "debit":
            continue
        if is_ignored_for_forecast(ev):
            continue
        
        # Exclude explicitly cancelled or failed events
        if getattr(ev, "status", "") in ["cancelled", "failed"]:
            continue
            
        eff_date = ev.settlement_date or ev.event_date
        if eff_date < today:
            continue
            
        key = ev.category or getattr(ev, "description", None) or ev.event_id
        
        if key in upcoming_by_key:
            existing_date = upcoming_by_key[key].settlement_date or upcoming_by_key[key].event_date
            if eff_date < existing_date:
                upcoming_by_key[key] = ev
        else:
            upcoming_by_key[key] = ev
            
    items = []
    protected_total = Decimal(0)
    flexible_total = Decimal(0)
    
    for ev in upcoming_by_key.values():
        is_protected = is_essential_outflow(ev, twin.profile)
        is_flexible = is_flexible_outflow(ev, twin.profile)
        
        amt = ev.amount or Decimal(0)
        
        if is_protected:
            protected_total += amt
        elif is_flexible:
            flexible_total += amt
            
        # If the event was generated by RecurringPatternDetector, it is recurring
        freq = "monthly" if getattr(ev, "status", "") == "projected" else "one-time"
        
        items.append(ExpenseItem(
            id=ev.event_id,
            name=ev.category.replace("_", " ").title() if ev.category else "Expense",
            category=ev.category,
            amount=amt,
            currency=ev.currency or "INR",
            frequency=freq,
            next_date=ev.settlement_date or ev.event_date,
            flexibility=ev.flexibility,
            is_protected=is_protected
        ))
        
    return ExpensesResponse(
        items=items,
        summary=ExpenseSummary(
            total_relevant=len(items),
            protected_total=protected_total,
            flexible_total=flexible_total
        )
    )
